import { createContext, useContext, useEffect, useMemo, useState } from 'react';

const languages = [
  { code: 'en', label: 'English' },
  { code: 'hi', label: 'हिन्दी' },
  { code: 'te', label: 'తెలుగు' },
  { code: 'ml', label: 'മലയാളം' },
  { code: 'ta', label: 'தமிழ்' },
  { code: 'kn', label: 'ಕನ್ನಡ' },
];

const translations = {
  en: {
    nav: {
      home: 'Home',
      courses: 'Courses',
      exams: 'Exams',
      leaderboard: 'Leaderboard',
      drives: 'Drives',
      contact: 'Contact',
      dashboard: 'Dashboard',
      createExam: 'Create Exam',
      manageDrives: 'Manage Drives',
      profile: 'Profile',
      login: 'Login',
      register: 'Register',
      logout: 'Logout',
      language: 'Language',
    },
    theme: {
      light: 'Light',
      dark: 'Dark',
    },
    landing: {
      heroBadge: 'Future-ready exam platform',
      heroTitle: 'A smarter exam experience for learners and educators.',
      heroSubtitle: 'EduPortal blends adaptive assessments, placement-ready analytics, and collaborative mentorship into a single modern learning hub.',
      exploreDrives: 'Explore Placement Drives',
      viewLeaderboard: 'View Leaderboard',
      trustedBy: 'Trusted by learners',
      studentLogin: 'Student Login',
      adminLogin: 'Admin Login',
      advancedTitle: 'Designed to feel different from every other exam platform.',
      advancedSubtitle: 'Smart guidance, real-time placement readiness, and interactive exam experiences keep learners engaged and motivated.',
      feature1Title: 'AI-powered Study Coach',
      feature1Text: 'Receive personalized revision tips, question recommendations, and exam readiness insights tailored to your progress.',
      feature2Title: 'Adaptive Exam Flow',
      feature2Text: 'Exams adapt to your pace and performance, giving more challenge where you need it and faster success tracking where you excel.',
      feature3Title: 'Placement Drive Hub',
      feature3Text: 'Discover real company drives, apply with your profile, and follow a career path that connects exam success to job readiness.',
      chooseTitle: 'Why Choose EduPortal?',
      choose1Title: 'Interactive exams',
      choose1Text: 'Real-time grading, instant feedback and immersive exam formats.',
      choose2Title: 'Course mastery',
      choose2Text: 'Structured modules, videos, and exercises that support real learning.',
      choose3Title: 'Deep analytics',
      choose3Text: 'Progress dashboards, score distributions, and exam strengths at a glance.',
      choose4Title: 'Career-ready',
      choose4Text: 'Built-in placement drives, ranking impact, and resume-ready achievement tracking.',
      quickLinksTitle: 'Quick links',
      quickLinksCourses: 'Browse courses and enroll in your next learning path.',
      quickLinksExams: 'Access active exams and practice tests.',
      quickLinksLeaderboard: 'Check rankings, score trends, and top performers.',
      quickLinksDrives: 'View available company drives and apply now.',
      getStartedTitle: 'Begin your journey with a modern exam portal.',
      studentPortal: 'Student Portal',
      studentPortalText: 'Study smarter with adaptive exams, learning analytics, and a placement-ready journey.',
      adminPortal: 'Admin Portal',
      adminPortalText: 'Build exams, review performance, and manage drives with a modern dashboard.',
    },
    auth: {
      signInTitle: 'Sign in to your account',
      registerTitle: 'Create your account',
      createAccountLink: 'create a new account',
      signInLink: 'sign in to existing account',
      emailAddress: 'Email address',
      password: 'Password',
      signIn: 'Sign in',
      signingIn: 'Signing in...',
      fullName: 'Full Name',
      confirmPassword: 'Confirm Password',
      role: 'Role',
      student: 'Student',
      admin: 'Admin',
      createAccount: 'Create account',
      creatingAccount: 'Creating account...',
      passwordsMismatch: 'Passwords do not match',
    },
    dashboard: {
      welcome: 'Welcome to your Dashboard, {name}!',
      totalUsers: 'Total Users',
      totalExams: 'Total Exams',
      totalCourses: 'Total Courses',
      totalSubmissions: 'Total Submissions',
      coursesEnrolled: 'Courses Enrolled',
      examsTaken: 'Exams Taken',
      averageScore: 'Average Score',
      passedExams: 'Passed Exams',
      loading: 'Loading dashboard...',
      loginRequired: 'Please login to access dashboard',
      scoreDistribution: 'Score Distribution',
      monthlyPerformance: 'Monthly Performance (Last 6 Months)',
      courseProgress: 'Course Progress',
      examsTakenLabel: 'Exams Taken',
      averageScoreLabel: 'Average Score (%)',
      progressLabel: 'Progress (%)',
    },
    courses: {
      title: 'Courses',
      addCourse: 'Add New Course',
      allCourses: 'All Courses',
      myCourses: 'My Courses',
      searchPlaceholder: 'Search courses...',
      allLevels: 'All Levels',
      beginner: 'Beginner',
      intermediate: 'Intermediate',
      advanced: 'Advanced',
      instructor: 'Instructor',
      hours: 'hours',
      enroll: 'Enroll',
      enrolled: 'Enrolled',
      noCoursesMatch: 'No courses match your search.',
      noEnrolled: "You haven't enrolled in any courses yet.",
      loading: 'Loading courses...',
    },
    exams: {
      title: 'Exams',
      duration: 'Duration:',
      totalMarks: 'Total Marks:',
      difficulty: 'Difficulty:',
      passed: 'Passed',
      failed: 'Failed',
      alreadySubmitted: 'Already submitted',
      reviewExam: 'Review Exam',
      takeExam: 'Take Exam',
      loginToTakeExam: 'Login to take exam',
      noExams: 'No exams available at the moment.',
      loading: 'Loading exams...',
      timerLabel: 'Timer:',
      passingScore: 'Passing Score:',
      examSubmitted: 'Exam Submitted',
      scoreLabel: 'Score:',
      percentageLabel: 'Percentage:',
      statusLabel: 'Status:',
      submitExam: 'Submit Exam',
      submitting: 'Submitting...',
      timeUp: 'Time is up. Please submit your answers now.',
      answerPlaceholder: 'Write your answer here',
      selectLanguage: 'Select Programming Language:',
      codePlaceholder: 'Write your {language} code solution here...',
      loginRequired: 'Please login to take this exam.',
      examNotFound: 'Exam not found.',
      noQuestions: 'This exam has no questions yet.',
    },
    drives: {
      title: 'Placement Drives',
      subtitle: 'Apply for company placement drives and kickstart your career',
      applyNow: 'Apply Now',
      deadlinePassed: 'Deadline Passed',
      noDrives: 'No active placement drives available at the moment.',
      loading: 'Loading drives...',
      applyFor: 'Apply for',
      fullName: 'Full Name *',
      email: 'Email *',
      cgpa: 'CGPA *',
      phone: 'Phone Number',
      address: 'Address',
      skills: 'Skills',
      experience: 'Experience',
      submitApplication: 'Submit Application',
      applicationSubmitted: 'Application submitted successfully!',
    },
    contact: {
      titleSmall: 'Contact us',
      title: 'We’re here to help you succeed.',
      subtitle: 'Have questions about courses, exams, or admin features? Send us a message and our EduPortal team will respond shortly.',
      emailTitle: 'Email',
      phoneTitle: 'Phone',
      officeTitle: 'Office',
      officeText: 'Online learning platform — available globally.',
      name: 'Name',
      message: 'Message',
      sendMessage: 'Send Message',
      thankYou: 'Thanks! Your message has been received.',
    },
    profile: {
      title: 'Profile',
      editProfile: 'Edit Profile',
      save: 'Save',
      cancel: 'Cancel',
      saving: 'Saving...',
      profileSaved: 'Profile saved successfully.',
      loginRequired: 'Please login to access profile',
      name: 'Name',
      email: 'Email',
      role: 'Role',
      placementInfo: 'Placement Information',
      phoneNumber: 'Phone Number',
      cgpa: 'CGPA',
      address: 'Address',
      skills: 'Skills',
      experience: 'Experience',
      profileImage: 'Profile image URL',
      notProvided: 'Not provided',
    },
    footer: {
      description: 'Empowering learners with interactive exams, courses, and analytics.',
      allRights: 'All rights reserved.',
    },
    notFound: {
      pageNotFound: 'Page not found',
      message: 'The page you are looking for does not exist. Head back to the homepage or explore your dashboard.',
    },
    admin: {
      dashboardTitle: 'Admin Dashboard',
      manageUsers: 'Manage Users',
      manageUsersText: 'View and manage all users',
      createExam: 'Create Exam',
      createExamText: 'Create new exams with questions',
      manageCourses: 'Manage Courses',
      manageCoursesText: 'Add and manage course content',
      createCourse: 'Create Course',
      courseBuilderTitle: 'Admin Course Builder',
      createNewCourse: 'Create New Course',
      manageCoursesTitle: 'Manage Courses',
      modulesForCourse: 'Modules for {title}',
      addModule: 'Add Module',
      createCourseSuccess: 'Course created. You can now add modules.',
      moduleAdded: 'Module added successfully',
      createCourseButton: 'Create Course',
      refreshModules: 'Refresh Modules',
      editDrive: 'Edit Drive',
      createNewDrive: 'Create New Drive',
      managePlacementDrives: 'Manage Placement Drives',
      managePlacementDrivesText: 'Create and manage company placement drives',
      createDrive: 'Create Drive',
      active: 'Active',
      inactive: 'Inactive',
      viewApplications: 'View Applications',
      deleteDriveConfirm: 'Are you sure you want to delete this drive?',
      errorSaveDrive: 'Error saving drive',
      noDrives: 'No drives created yet. Click "Create Drive" to add your first placement drive.',
    },
  },
  hi: {
    nav: {
      home: 'होम',
      courses: 'पाठ्यक्रम',
      exams: 'परीक्षाएँ',
      leaderboard: 'लीडरबोर्ड',
      drives: 'ड्राइव्स',
      contact: 'संपर्क',
      dashboard: 'डैशबोर्ड',
      createExam: 'परीक्षा बनाएँ',
      manageDrives: 'ड्राइव्स प्रबंधित करें',
      profile: 'प्रोफ़ाइल',
      login: 'लॉग इन',
      register: 'रजिस्टर',
      logout: 'लॉग आउट',
      language: 'भाषा',
    },
    theme: {
      light: 'लाइट',
      dark: 'डार्क',
    },
    landing: {
      heroBadge: 'भविष्य के तैयार परीक्षा मंच',
      heroTitle: 'सीखने वालों और शिक्षकों के लिए स्मार्ट परीक्षा अनुभव।',
      heroSubtitle: 'EduPortal अनुकूलनात्मक आकलन, प्लेसमेंट-तैयार विश्लेषण, और सहयोगी मेंटरशिप को एक आधुनिक लर्निंग हब में समेटता है।',
      exploreDrives: 'प्लेसमेंट ड्राइव्स देखें',
      viewLeaderboard: 'लीडरबोर्ड देखें',
      trustedBy: 'सीखने वालों द्वारा भरोसा किया गया',
      studentLogin: 'स्टूडेंट लॉगिन',
      adminLogin: 'एडमिन लॉगिन',
      advancedTitle: 'हर दूसरे परीक्षा प्लेटफ़ॉर्म से अलग महसूस करने के लिए डिज़ाइन किया गया।',
      advancedSubtitle: 'स्मार्ट मार्गदर्शन, वास्तविक समय प्लेसमेंट तैयारी और इंटरैक्टिव परीक्षा अनुभव आपको जोश बनाए रखते हैं।',
      feature1Title: 'एआई-संचालित स्टडी कोच',
      feature1Text: 'व्यक्तिगत संशोधन सुझाव, प्रश्न अनुशंसाएं और आपकी प्रगति के अनुसार तैयारी अंतर्दृष्टि प्राप्त करें।',
      feature2Title: 'अनुकूली परीक्षा फ्लो',
      feature2Text: 'परीक्षाएँ आपकी गति और प्रदर्शन के अनुसार अनुकूलित होती हैं, जिससे जहां ज़रूरत हो अधिक चुनौती और बेहतर सफलता ट्रैकिंग मिले।',
      feature3Title: 'प्लेसमेंट ड्राइव हब',
      feature3Text: 'वास्तविक कंपनी ड्राइव खोजें, अपने प्रोफ़ाइल के साथ आवेदन करें, और नौकरी तैयारियों से जुड़ी यात्रा का पालन करें।',
      chooseTitle: 'EduPortal क्यों चुनें?',
      choose1Title: 'इंटरएक्टिव परीक्षा',
      choose1Text: 'रियल-टाइम ग्रेडिंग, त्वरित प्रतिक्रिया और इमर्सिव परीक्षा स्वरूप।',
      choose2Title: 'कोर्स मास्टरी',
      choose2Text: 'संरचित मॉड्यूल, वीडियो, और अभ्यास जो वास्तविक सीखने का समर्थन करते हैं।',
      choose3Title: 'गहन विश्लेषण',
      choose3Text: 'प्रगति डैशबोर्ड, स्कोर वितरण, और ताकतों की एक झलक।',
      choose4Title: 'कैरियर-रेडी',
      choose4Text: 'इनबिल्ट प्लेसमेंट ड्राइव, रैंकिंग प्रभाव, और रिज़्यूमे-तयारी ट्रैकिंग।',
      quickLinksTitle: 'त्वरित लिंक्स',
      quickLinksCourses: 'पाठ्यक्रम ब्राउज़ करें और अपनी अगली सीखने की यात्रा में नामांकन करें।',
      quickLinksExams: 'सक्रिय परीक्षाओं और अभ्यास टेस्ट तक पहुँचें।',
      quickLinksLeaderboard: 'रैंकिंग, स्कोर प्रवृत्तियाँ, और शीर्ष प्रदर्शन देखें।',
      quickLinksDrives: 'उपलब्ध कंपनी ड्राइव देखें और अभी आवेदन करें।',
      getStartedTitle: 'आधुनिक परीक्षा पोर्टल के साथ अपनी यात्रा शुरू करें।',
      studentPortal: 'छात्र पोर्टल',
      studentPortalText: 'अनुकूली परीक्षाएँ, सीखने का विश्लेषण, और प्लेसमेंट-तैयार यात्रा के साथ स्मार्ट पढ़ाई करें।',
      adminPortal: 'एडमिन पोर्टल',
      adminPortalText: 'परीक्षाएँ बनाएं, प्रदर्शन की समीक्षा करें, और आधुनिक डैशबोर्ड के साथ ड्राइव्स प्रबंधित करें।',
    },
    auth: {
      signInTitle: 'अपने खाते में साइन इन करें',
      registerTitle: 'अपना खाता बनाएं',
      createAccountLink: 'एक नया खाता बनाएं',
      signInLink: 'मौजूदा खाते में साइन इन करें',
      emailAddress: 'ईमेल पता',
      password: 'पासवर्ड',
      signIn: 'साइन इन',
      signingIn: 'साइन इन हो रहा है...',
      fullName: 'पूरा नाम',
      confirmPassword: 'पासवर्ड की पुष्टि करें',
      role: 'भूमिका',
      student: 'छात्र',
      admin: 'प्रशासक',
      createAccount: 'खाता बनाएं',
      creatingAccount: 'खाता बनाया जा रहा है...',
      passwordsMismatch: 'पासवर्ड मेल नहीं खाते',
    },
    dashboard: {
      welcome: 'आपके डैशबोर्ड में आपका स्वागत है, {name}!',
      totalUsers: 'कुल उपयोगकर्ता',
      totalExams: 'कुल परीक्षाएँ',
      totalCourses: 'कुल पाठ्यक्रम',
      totalSubmissions: 'कुल सबमिशन',
      coursesEnrolled: 'नामांकित पाठ्यक्रम',
      examsTaken: 'लिइ गई परीक्षाएँ',
      averageScore: 'औसत स्कोर',
      passedExams: 'उत्तीर्ण परीक्षाएँ',
      loading: 'डैशबोर्ड लोड हो रहा है...',
      loginRequired: 'डैशबोर्ड तक पहुँचने के लिए कृपया लॉगिन करें',
      scoreDistribution: 'स्कोर वितरण',
      monthlyPerformance: 'मासिक प्रदर्शन (पिछले 6 महीने)',
      courseProgress: 'कोर्स प्रगति',
      examsTakenLabel: 'लिइ गई परीक्षाएँ',
      averageScoreLabel: 'औसत स्कोर (%)',
      progressLabel: 'प्रगति (%)',
    },
    courses: {
      title: 'पाठ्यक्रम',
      addCourse: 'नया पाठ्यक्रम जोड़ें',
      allCourses: 'सभी पाठ्यक्रम',
      myCourses: 'मेरे पाठ्यक्रम',
      searchPlaceholder: 'पाठ्यक्रम खोजें...',
      allLevels: 'सभी स्तर',
      beginner: 'शुरुआती',
      intermediate: 'मध्यम',
      advanced: 'उन्नत',
      instructor: 'प्रशिक्षक',
      hours: 'घंटे',
      enroll: 'नामांकन करें',
      enrolled: 'नामांकित',
      noCoursesMatch: 'आपकी खोज से कोई पाठ्यक्रम मेल नहीं खाता।',
      noEnrolled: 'आपने अभी तक किसी पाठ्यक्रम में नामांकन नहीं किया है।',
      loading: 'पाठ्यक्रम लोड हो रहे हैं...',
    },
    exams: {
      title: 'परीक्षाएँ',
      duration: 'अवधि:',
      totalMarks: 'कुल अंक:',
      difficulty: 'कठिनाई:',
      passed: 'उत्तीर्ण',
      failed: 'अनुत्तीर्ण',
      alreadySubmitted: 'पहले ही जमा कर दिया गया',
      reviewExam: 'परीक्षा की समीक्षा करें',
      takeExam: 'परीक्षा दें',
      loginToTakeExam: 'परीक्षा देने के लिए लॉगिन करें',
      noExams: 'इस समय कोई परीक्षा उपलब्ध नहीं है।',
      loading: 'परीक्षाएँ लोड हो रही हैं...',
      timerLabel: 'टाइमर:',
      passingScore: 'उत्तीर्ण अंक:',
      examSubmitted: 'परीक्षा जमा की गयी',
      scoreLabel: 'स्कोर:',
      percentageLabel: 'प्रतिशत:',
      statusLabel: 'स्थिति:',
      submitExam: 'परीक्षा जमा करें',
      submitting: 'जमा किया जा रहा है...',
      timeUp: 'समय समाप्त हो गया है। कृपया अब अपने उत्तर जमा करें।',
      answerPlaceholder: 'अपना उत्तर यहां लिखें',
      selectLanguage: 'प्रोग्रामिंग भाषा चुनें:',
      codePlaceholder: '{language} कोड समाधान यहां लिखें...',
      loginRequired: 'कृपया यह परीक्षा देने के लिए लॉगिन करें।',
      examNotFound: 'परीक्षा नहीं मिली।',
      noQuestions: 'इस परीक्षा में अभी कोई प्रश्न नहीं हैं।',
    },
    drives: {
      title: 'प्लेसमेंट ड्राइव्स',
      subtitle: 'कंपनी प्लेसमेंट ड्राइव्स के लिए आवेदन करें और अपने करियर की शुरुआत करें',
      applyNow: 'अब आवेदन करें',
      deadlinePassed: 'समय सीमा समाप्त',
      noDrives: 'इस समय कोई सक्रिय प्लेसमेंट ड्राइव उपलब्ध नहीं है।',
      loading: 'ड्राइव्स लोड हो रहे हैं...',
      applyFor: 'के लिए आवेदन करें',
      fullName: 'पूरा नाम *',
      email: 'ईमेल *',
      cgpa: 'सीजीपीए *',
      phone: 'फ़ोन नंबर',
      address: 'पता',
      skills: 'कौशल',
      experience: 'अनुभव',
      submitApplication: 'आवेदन जमा करें',
      applicationSubmitted: 'आवेदन सफलतापूर्वक जमा किया गया!',
    },
    contact: {
      titleSmall: 'संपर्क करें',
      title: 'हम आपकी सफलता में मदद करने के लिए यहाँ हैं।',
      subtitle: 'पाठ्यक्रम, परीक्षाओं, या एडमिन सुविधाओं के बारे में प्रश्न हैं? हमें संदेश भेजें और हमारी टीम शीघ्र उत्तर देगी।',
      emailTitle: 'ईमेल',
      phoneTitle: 'फ़ोन',
      officeTitle: 'ऑफ़िस',
      officeText: 'ऑनलाइन लर्निंग प्लेटफ़ॉर्म — वैश्विक रूप से उपलब्ध।',
      name: 'नाम',
      message: 'संदेश',
      sendMessage: 'संदेश भेजें',
      thankYou: 'धन्यवाद! आपका संदेश प्राप्त हो गया है।',
    },
    profile: {
      title: 'प्रोफ़ाइल',
      editProfile: 'प्रोफ़ाइल संपादित करें',
      save: 'सहेजें',
      cancel: 'रद्द करें',
      saving: 'सहेजा जा रहा है...',
      profileSaved: 'प्रोफ़ाइल सफलतापूर्वक सहेजी गई।',
      loginRequired: 'प्रोफ़ाइल तक पहुँचने के लिए कृपया लॉगिन करें',
      name: 'नाम',
      email: 'ईमेल',
      role: 'भूमिका',
      placementInfo: 'प्लेसमेंट जानकारी',
      phoneNumber: 'फ़ोन नंबर',
      cgpa: 'सीजीपीए',
      address: 'पता',
      skills: 'कौशल',
      experience: 'अनुभव',
      profileImage: 'प्रोफ़ाइल छवि यूआरएल',
      notProvided: 'प्रदान नहीं किया गया',
    },
    footer: {
      description: 'इंटरैक्टिव परीक्षाओं, पाठ्यक्रमों, और विश्लेषण के साथ शिक्षार्थियों को सशक्त बनाना।',
      allRights: 'सर्वाधिकार सुरक्षित।',
    },
    notFound: {
      pageNotFound: 'पेज नहीं मिला',
      message: 'आप जो पेज ढूंढ़ रहे हैं वह मौजूद नहीं है। होमपेज पर वापस जाएँ या अपने डैशबोर्ड का अन्वेषण करें।',
    },
    admin: {
      dashboardTitle: 'एडमिन डैशबोर्ड',
      manageUsers: 'उपयोगकर्ताओं का प्रबंधन करें',
      manageUsersText: 'सभी उपयोगकर्ताओं को देखें और प्रबंधित करें',
      createExam: 'परीक्षा बनाएँ',
      createExamText: 'प्रश्नों के साथ नई परीक्षाएँ बनाएं',
      manageCourses: 'पाठ्यक्रम प्रबंधित करें',
      manageCoursesText: 'पाठ्यक्रम सामग्री जोड़ें और प्रबंधित करें',
      createCourse: 'पाठ्यक्रम बनाएँ',
      courseBuilderTitle: 'एडमिन पाठ्यक्रम बिल्डर',
      createNewCourse: 'नया पाठ्यक्रम बनाएँ',
      manageCoursesTitle: 'पाठ्यक्रम प्रबंधित करें',
      modulesForCourse: '{title} के लिए मॉड्यूल',
      addModule: 'मॉड्यूल जोड़ें',
      createCourseSuccess: 'पाठ्यक्रम बनाया गया। अब आप मॉड्यूल जोड़ सकते हैं।',
      moduleAdded: 'मॉड्यूल सफलतापूर्वक जोड़ा गया',
      createCourseButton: 'पाठ्यक्रम बनाएँ',
      refreshModules: 'मॉड्यूल रिफ़्रेश करें',
      editDrive: 'ड्राइव संपादित करें',
      createNewDrive: 'नया ड्राइव बनाएँ',
      managePlacementDrives: 'प्लेसमेंट ड्राइव्स प्रबंधित करें',
      managePlacementDrivesText: 'कंपनी प्लेसमेंट ड्राइव्स बनाएं और प्रबंधित करें',
      createDrive: 'ड्राइव बनाएँ',
      active: 'सक्रिय',
      inactive: 'निष्क्रिय',
      viewApplications: 'आवेदन देखें',
      deleteDriveConfirm: 'क्या आप वाकई इस ड्राइव को हटाना चाहते हैं?',
      errorSaveDrive: 'ड्राइव सहेजने में त्रुटि',
      noDrives: 'अभी तक कोई ड्राइव नहीं बनाया गया है। अपना पहला प्लेसमेंट ड्राइव जोड़ने के लिए "Create Drive" पर क्लिक करें।',
    },
  },
  te: {
    nav: {
      home: 'హోమ్',
      courses: 'కోర్సులు',
      exams: 'పరీక్షలు',
      leaderboard: 'లీడర్‌బోర్డు',
      drives: 'డ్రైవ్‌లు',
      contact: 'సంప్రదించండి',
      dashboard: 'డ్యాశ్బోర్డు',
      createExam: 'పరీక్ష రూపొందించండి',
      manageDrives: 'డ్రైవ్‌లను నిర్వహించండి',
      profile: 'ప్రొఫైల్',
      login: 'లాగిన్',
      register: 'నమోదవ్వండి',
      logout: 'లాగ్ అవుట్',
      language: 'భాష',
    },
    theme: {
      light: 'లైట్',
      dark: 'డార్క్',
    },
    landing: {
      heroBadge: 'భవిష్యత్తుకి సిద్ధమైన పరీక్ష ప్లాట్‌ఫామ్',
      heroTitle: 'శిక్షణార్థులకు మరియు శిక్షకులకు శ్రేష్ట పరీక్ష అనుభవం.',
      heroSubtitle: 'EduPortal అనుకూల పరీక్షలు, ప్లేస్మెంట్-సన్నద్ధ విశ్లేషణ, మరియు సహకార శిక్షణలను ఒక ఆధునిక లెర్నింగ్ హబ్‌లో కలుపుతుంది.',
      exploreDrives: 'ప్లేస్మెంట్ డ్రైව්లను అన్వేషించండి',
      viewLeaderboard: 'లీడర్‌బోర్డును వీక్షించండి',
      trustedBy: 'అభ్యాసకుల విశ్వసనీయత',
      studentLogin: 'స్టూడెంట్ లాగిన్',
      adminLogin: 'అడ్మిన్ లాగిన్',
      advancedTitle: 'ప్రతి ఇతర పరీక్ష ప్లాట్‌ఫామ్ నుండి విభిన్నంగా అనిపించేలా రూపొందించబడింది.',
      advancedSubtitle: 'స్మార్ట్ మార్గదర్శనం, రియల్-టైమ్ ప్లేస్‌మెంట్ సిద్ధత, మరియు ఇంటరాక్టివ్ పరీక్ష అనుభవాలు sizi ప్రేరేపిస్తాయి.',
      feature1Title: 'AI-చేరిన స్టడీ కోచ్',
      feature1Text: 'మీ పురోభివృద్ధికి అనుగుణంగా వ్యక్తిగత సవరణ సూచనలు, ప్రశ్న సిఫార్సులు, మరియు పరీక్ష సిద్ధత అవగాహన పొందండి.',
      feature2Title: 'అనుకూల పరీక్ష ప్రవాహం',
      feature2Text: 'మీ వేగం మరియు ప్రదర్శనకు అనుగుణంగా పరీక్షలు సర్దుబాటు చేస్తాయి.',
      feature3Title: 'ప్లేస్మెంట్ డ్రైవ్ హబ్',
      feature3Text: 'నిజమైన కంపెనీ డ్రైవ్‌లను కనుగొనండి, మీ ప్రొఫైల్‌తో దరఖాస్తు చేయండి, మరియు ఉద్యోగానికి సిద్ధతను కొనసాగించండి.',
      chooseTitle: 'ఎడుపోర్టల్‌ను ఎందుకు ఎంచుకోవాలి?',
      choose1Title: 'ఇంటరాక్టివ్ పరీక్షలు',
      choose1Text: 'తక్షణ ఫీడ్‌బ్యాక్ మరియు ఆసక్తికర పరీక్ష రూపాల్లో నిజ కాలం గ్రేడింగ్.',
      choose2Title: 'కోర్సు ప్రావీణ్యం',
      choose2Text: 'వ్యవస్థాగత మాడ్యూల్స్, వీడియోలు, మరియు వ్యాయామాలు వాస్తవ అభ్యాసాన్ని మద్దతు చేస్తాయి.',
      choose3Title: 'లోతైన విశ్లేషణ',
      choose3Text: 'ప్రగతి డ్యాష్‌బోర్డులు, స్కోరు పంపిణీ, మరియు బలం తక్షణ దర్శనం.',
      choose4Title: 'కెరీర్-సిద్ధం',
      choose4Text: 'అంతర్లీన ప్లేస్మెంట్ డ్రైవ్‌లు, ర్యాంకింగ్ ప్రభావం, మరియు రిజ్యూమ్ సిద్ధత ట్రాకింగ్.',
      quickLinksTitle: 'త్వరిత లింకులు',
      quickLinksCourses: 'కోర్సులను బ్రౌజ్ చేయండి మరియు మీ తదుపరి అభ్యాస మార్గంలో నమోదు చేసుకోండి.',
      quickLinksExams: 'క్రియాశీల పరీక్షలు మరియు ప్రాక్టీస్ టెస్టులకు ప్రాప్తి పొందండి.',
      quickLinksLeaderboard: 'ర్యాంకింగ్‌లు, స్కోరు ధోరణులు మరియు టాప్ ప్రదర్శనలను తనిఖీ చేయండి.',
      quickLinksDrives: 'అందుబాటులో ఉన్న కంపెనీ డ్రైవ్‌లను చూడండి మరియు ఇప్పుడే దరఖాస్తు చేయండి.',
      getStartedTitle: 'ఆధునిక పరీక్ష పోర్టల్‌తో మీ ప్రయాణం ప్రారంభించండి.',
      studentPortal: 'స్టూడెంట్ పోర్టల్',
      studentPortalText: 'అనుకూల పరీక్షలు, అభ్యాస విశ్లేషణ మరియు ప్లేస్మెంట్-పూర్తయిన ప్రయాణంతో తెలివైన చదువు.',
      adminPortal: 'అడ్మిన్ పోర్టల్',
      adminPortalText: 'పరీక్షలను నిర్మించండి, పనితీరును సమీక్షించండి, మరియు ఆధునిక డ్యాష్‌బోర్డుతో డ్రైవ్‌లను నిర్వహించండి.',
    },
    auth: {
      signInTitle: 'మీ ఖాతాలో సైన్ ఇన్ చేయండి',
      registerTitle: 'మీ ఖాతాను సృష్టించండి',
      createAccountLink: 'కొత్త ఖాతాను పుట్టించండి',
      signInLink: 'ఉన్న ఖాతాలో సైన్ ఇన్ చేయండి',
      emailAddress: 'ఇమెయిల్ చిరునామా',
      password: 'పాస్వర్డ్',
      signIn: 'సైన్ ఇన్',
      signingIn: 'సైన్ ఇన్ అవుతోంది...',
      fullName: 'పూర్తి పేరు',
      confirmPassword: 'పాస్వర్డ్‌ను నిర్ధారించండి',
      role: 'పాత్ర',
      student: 'విద్యార్థి',
      admin: 'నిర్వాహకుడు',
      createAccount: 'ఖాతాను సృష్టించండి',
      creatingAccount: 'ఖాతాను సృష్టిస్తున్నాం...',
      passwordsMismatch: 'పాస్వర్డ్‌లు సరిపడవు',
    },
    dashboard: {
      welcome: 'మీ డ్యాష్బోర్డ్కు స్వాగతం, {name}!',
      totalUsers: 'మొత్తం వినియోగదారులు',
      totalExams: 'మొత్తం పరీక్షలు',
      totalCourses: 'మొత్తం కోర్సులు',
      totalSubmissions: 'మొత్తం సమర్పణలు',
      coursesEnrolled: 'రెజిస్టర్ అయిన కోర్సులు',
      examsTaken: 'అనుబంధ పరీక్షలు',
      averageScore: 'సగటు స్కోరు',
      passedExams: 'ఉత్తీర్ణ పరీక్షలు',
      loading: 'డ్యాష్బోర్డు లోడ్ అవుతోంది...',
      loginRequired: 'డ్యాష్బోర్డ్కు యాక్సెస్ చేసుకోవడానికి దయచేసి లాగిన్ చేయండి',
      scoreDistribution: 'స్కోరు పంపిణీ',
      monthlyPerformance: 'మాసంవారీ పనితీరు (గత 6 నెలలు)',
      courseProgress: 'కోర్సు పురోగతి',
      examsTakenLabel: 'పరీక్షలు తీసుకున్నాయి',
      averageScoreLabel: 'సగటు స్కోరు (%)',
      progressLabel: 'ప్రగతి (%)',
    },
    courses: {
      title: 'కోర్సులు',
      addCourse: 'కొత్త కోర్సు జోడించండి',
      allCourses: 'అన్ని కోర్సులు',
      myCourses: 'నా కోర్స్‌లు',
      searchPlaceholder: 'కోర్సులను శోధించండి...',
      allLevels: 'అన్ని స్థాయులు',
      beginner: 'ప్రారంభ స్థాయి',
      intermediate: 'మధ్యస్థం',
      advanced: 'అధిక',
      instructor: 'శిక్షకుడు',
      hours: 'గంటలు',
      enroll: 'రెజిస్టర్ చేయండి',
      enrolled: 'రెజిస్టర్ అయింది',
      noCoursesMatch: 'మీ శోధన మీకు ఏ కోర్సు కూడా కనపడలేదు.',
      noEnrolled: 'మీరు ఇంకా ఏ కోర్సులోనైనా నమోదు కాలేదని.',
      loading: 'కోర్సులు లోడ్ అవుతున్నాయి...',
    },
    exams: {
      title: 'పరీక్షలు',
      duration: ' వ్యవధి:',
      totalMarks: 'మొత్తం మార్కులు:',
      difficulty: 'పనికిరాని:',
      passed: 'ఉత్తీర్ణ',
      failed: 'నిరస్థ',
      alreadySubmitted: 'ఇప్పటికే సమర్పించారు',
      reviewExam: 'పరీక్షను సమీక్షించండి',
      takeExam: 'పరీక్ష తీసుకోండి',
      loginToTakeExam: 'పరీక్షకు లాగిన్ చేయండి',
      noExams: 'ప్రస్తుతం ఎలాంటి పరీక్షలు అందుబాటులో లేవు.',
      loading: 'పరీక్షలు లోడ్ అవుతున్నాయి...',
      timerLabel: 'టైమర్:',
      passingScore: 'ఉత్తీర్ణ మార్కు:',
      examSubmitted: 'పరీక్ష సమర్పించబడింది',
      scoreLabel: 'స్కోరు:',
      percentageLabel: 'శాతం:',
      statusLabel: 'స్థితి:',
      submitExam: 'పరీక్షను సమర్పించండి',
      submitting: 'సమర్పిస్తున్నాం...',
      timeUp: 'సమయం పూర్తయిపోయింది. దయచేసి ఇప్పుడు మీ సమాధానాలను సమర్పించండి.',
      answerPlaceholder: 'మీ సమాధానాన్ని ఇక్కడ రాయండి',
      selectLanguage: 'ప్రోగ్రామింగ్ భాషను ఎంచుకోండి:',
      codePlaceholder: '{language} కోడ్ పరిష్కారాన్ని ఇక్కడ రాయండి...',
      loginRequired: 'దయచేసి ఈ परीक्षा ఇవ్వడానికి లాగిన్ చేయండి.',
      examNotFound: 'పరీక్ష కనపడలేదు.',
      noQuestions: 'ఈ పరీక్షలో ఇంకా ప్రశ్నలు లేవు.',
    },
    drives: {
      title: 'ప్లేస్‌మెంట్ డ్రైవ్‌లు',
      subtitle: 'కంపెనీ ప్లేస్‌మెంట్ డ్రైవ్‌లకు దరఖాస్తు చేయండి మరియు మీ కెరీర్‌ను ప్రారంభించండి',
      applyNow: 'ఇప్పుడే దరఖాస్తు చేయండి',
      deadlinePassed: 'డెడ్‌లైన్ ముగిసింది',
      noDrives: 'ప్రస్తుతం యాక్టివ్ ప్లేస్‌మెంట్ డ్రైవ్‌లు లేవు.',
      loading: 'డ్రైవ్‌లు లోడ్ అవుతున్నాయి...',
      applyFor: 'కోసం దరఖాస్తు చేయండి',
      fullName: 'పూర్తి పేరు *',
      email: 'ఇమెయిల్ *',
      cgpa: 'CGPA *',
      phone: 'ఫోన్ నెంబరు',
      address: 'చిరునామా',
      skills: 'నైపుణ్యాలు',
      experience: 'అనుభవం',
      submitApplication: 'అప్లికేషన్ సమర్పించండి',
      applicationSubmitted: 'అప్లికేషన్ విజయవంతంగా సమర్పించబడింది!',
    },
    contact: {
      titleSmall: 'సంప్రదించండి',
      title: 'మీ విజయానికి మేము సహాయం చేసేందుకు ఇక్కడ ఉన్నాము.',
      subtitle: 'పాఠ్యక్రమాలు, పరీక్షలు, లేదా అడ్మిన్ ఫీచర్ల గురించి ప్రశ్నలున్నాయే? మాకు సందేశం పంపండి మరియు మా టీమ్ త్వరలో జవాబిస్తుంది.',
      emailTitle: 'ఇమెయిల్',
      phoneTitle: 'ఫోన్',
      officeTitle: 'ఆఫీస్',
      officeText: 'ఆన్‌లైన్ లెర్నింగ్ ప్లాట్‌ఫామ్ — ప్రపంచవ్యాప్తంగా అందుబాటులో ఉంది.',
      name: 'పేరు',
      message: 'సందేశం',
      sendMessage: 'సందేశం పంపండి',
      thankYou: 'ధన్యవాదాలు! మీ సందేశం స్వీకరించబడింది.',
    },
    profile: {
      title: 'ప్రొఫైల్',
      editProfile: 'ప్రొఫైల్‌ను సవరించు',
      save: 'సేవ్ చేయండి',
      cancel: 'రద్దు చేయండి',
      saving: 'సేవ్ అవుతోంది...',
      profileSaved: 'ప్రొఫైల్ విజయవంతంగా సేవ్ అయ్యింది.',
      loginRequired: 'ప్రొఫైల్‌కి యాక్సెస్ చేయడానికి దయచేసి లాగిన్ చేయండి',
      name: 'పేరు',
      email: 'ఇమెయిల్',
      role: 'పాత్ర',
      placementInfo: 'ప్లేస్మెంట్ సమాచారం',
      phoneNumber: 'ఫోన్ నంబరు',
      cgpa: 'CGPA',
      address: 'చిరునామా',
      skills: 'నైపుణ్యాలు',
      experience: 'అనుభవం',
      profileImage: 'ప్రొఫైల్ చిత్రం URL',
      notProvided: 'కొచ్చేటూ లేదు',
    },
    footer: {
      description: 'ఇంటరాక్టివ్ పరీక్షలు, కోర్సులు, మరియు విశ్లేషణలతో అభ్యాసకులను శక్తివంతం చేయడం.',
      allRights: 'అన్ని హక్కులు محفوظ ఉన్నాయి.',
    },
    notFound: {
      pageNotFound: 'పేజీ కనబడలేదు',
      message: 'మీరు చూస్తున్న పేజీ లేదు. హోమ్‌పేజికి తిరిగి వెళ్లండి లేదా మీ డ్యాష్‌బోర్డ్ను అన్వేషించండి.',
    },
    admin: {
      dashboardTitle: 'అడ్మిన్ డ్యాష్‌బోర్లు',
      manageUsers: 'వినియోగదారులను నిర్వహించండి',
      manageUsersText: 'అన్ని వినియోగదారులను చూడండి మరియు నిర్వహించండి',
      createExam: 'పరీక్షను సృష్టించండి',
      createExamText: 'ప్రశ్నలతో కొత్త పరీక్షలను సృష్టించండి',
      manageCourses: 'కోర్సులను నిర్వహించండి',
      manageCoursesText: 'కోర్సు కంటెంట్‌ని జోడించండి మరియు నిర్వహించండి',
      createCourse: 'కోర్సు సృష్టించండి',
      courseBuilderTitle: 'అడ్మిన్ కోర్సు బిల్డర్',
      createNewCourse: 'కొత్త కోర్సు సృష్టించండి',
      manageCoursesTitle: 'కోర్సులను నిర్వహించండి',
      modulesForCourse: '{title} కోసం మాడ్యూల్స్',
      addModule: 'మాడ్యూల్ జోడించండి',
      createCourseSuccess: 'కోర్సు సృష్టించబడింది. ఇప్పుడు మీరు మాడ్యూల్స్‌ని జోడించవచ్చు.',
      moduleAdded: 'మాడ్యూల్ విజయవంతంగా జోడించబడింది',
      createCourseButton: 'కోర్సు సృష్టించండి',
      refreshModules: 'మాడ్యూల్స్‌ని రిఫ్రెష్ చేయండి',
      editDrive: 'డ్రైవ్‌ను ఎడిట్ చేయండి',
      createNewDrive: 'కొత్త డ్రైవ్ సృష్టించండి',
      managePlacementDrives: 'ప్లేస్‌మెంట్ డ్రైవ్‌లను నిర్వహించండి',
      managePlacementDrivesText: 'కంపెనీ ప్లేస్‌మెంట్ డ్రైవ్‌లు సృష్టించండి మరియు నిర్వహించండి',
      createDrive: 'డ్రైవ్ సృష్టించండి',
      active: 'క్రియాశీల',
      inactive: 'నిష్క్రియ',
      viewApplications: 'అప్లికేషన్లను వీక్షించండి',
      deleteDriveConfirm: 'మీరు నిజంగా ఈ డ్రైవ్‌ను తొలగించాలనుకుంటున్నారా?',
      errorSaveDrive: 'డ్రైవ్‌ని సేవ్ చేయడంలో లోపం',
      noDrives: 'మొదటి ప్లేస్‌మెంట్ డ్రైవ్‌ను జోడించడానికి "Create Drive" క్లిక్ చేయండి.',
    },
  },
  ml: {
    nav: {
      home: 'ഹോം',
      courses: 'കോഴ്സുകൾ',
      exams: 'പരീക്ഷകൾ',
      leaderboard: 'ലീഡർബോർഡ്',
      drives: 'ഡ്രൈവിംഗുകൾ',
      contact: 'ബന്ധപ്പെടാം',
      dashboard: 'ഡാഷ്‌ബോർഡ്',
      createExam: 'പരീക്ഷ സൃഷ്ടിക്കുക',
      manageDrives: 'ഡ്രൈവിംଗുകൾ നടത്തുക',
      profile: 'പ്രൊഫൈൽ',
      login: 'ലോഗിൻ',
      register: 'രജിസ്റ്റർ',
      logout: 'ലോഗ് ഔട്ട്',
      language: 'ഭാഷ',
    },
    theme: {
      light: 'ലെറ്റ്',
      dark: 'ഡാർക്ക്',
    },
    landing: {
      heroBadge: 'ഭാവി-സജ്ജമായ പരീക്ഷ പ്ലാറ്റ്ഫോം',
      heroTitle: 'വിദ്യാർത്ഥികളെയും അധ്യാപകരെയും 위한 ബുദ്ധിമുട്ടുള്ള പരീക്ഷ അനുഭവം.',
      heroSubtitle: 'EduPortal അനുകൂലമാക്കിയ അടയാളങ്ങൾ, പ്ലേസ്‌മെന്റ്-തയാറായ വിശകലനങ്ങൾ, ಮತ್ತು സഹകരണമേറിയ മെന്റർഷിപ്പ് ഒരു ആധുനിക പഠന ഹബിൽ ഉൾക്കൊള്ളിക്കുന്നു.',
      exploreDrives: 'പ്ലേസ്‌മെന്റ് ഡ്രൈവ് കാണുക',
      viewLeaderboard: 'ലീഡർബോർഡ് കാണുക',
      trustedBy: 'വിദ്യാർത്ഥികൾ വിശ്വസിക്കുന്നു',
      studentLogin: 'വിദ്യാർത്ഥി ലോഗിൻ',
      adminLogin: 'അഡ്‌മിൻ ലോഗിൻ',
      advancedTitle: 'മറ്റേതെങ്കിലും പരീക്ഷ പ്ലാറ്റ്ഫോമിൽ നിന്നും വ്യത്യസ്ഥമായി അനുഭവിക്കാൻ രൂപകൽപ്പന ചെയ്യപ്പെട്ടത്.',
      advancedSubtitle: 'സ്മാർട്ട് മാർഗനിർദേശം, റിയൽ-ടൈം പ്ലേസ്‌മെന്റ് തയ്യാറെടുപ്പ്, ആഡ്-അംഗം പരീക്ഷ അനുഭവങ്ങൾ നിങ്ങളെ പ്രചോദിപ്പിക്കുന്നു.',
      feature1Title: 'AI-പ്രോത്സാഹിപ്പിച്ച പഠന കോച്ച്',
      feature1Text: 'നിങ്ങളുടെ പുരോഗതിയുടെ അടിസ്ഥാനത്തിൽ വ്യക്തിഗത പഠന നിർദേശങ്ങൾ, ചോദ്യ ശുപാർശകൾ, പരീക്ഷ തയ്യാറെടുപ്പ്洞öger ',
      feature2Title: 'അനുകൂല പരീക്ഷ പ്രവാഹം',
      feature2Text: 'നിങ്ങളുടെ താത്പര്യവും പ്രകടനവും പ്രതിപാദിച്ചാൽ പരീക്ഷകൾ കഠിനതയിൽ‌വരെ ചേര്‍ക്കും.',
      feature3Title: 'പ്ലേസ്‌മെന്റ് ഡ്രൈവ് ഹബ്',
      feature3Text: 'യഥാർത്ഥ കമ്പനിയുടെ ഡ്രൈവ് കണ്ടെത്തുക, നിങ്ങളുടെ പ്രൊഫൈലുമായി അപേക്ഷിക്കുക, ജോലി തയ്യാറെടുപ്പ് തുടരണം.',
      chooseTitle: 'എന്തുകൊണ്ട് EduPortal തിരഞ്ഞെടുക്കാം?',
      choose1Title: 'ഇന്ററാക്റ്റീവ് പരീക്ഷകൾ',
      choose1Text: 'റിയൽ-ടൈം ഗ്രേഡിംഗ്, ത್ವರിത പ്രതികരണം, ആകർഷക പരീക്ഷ ഫോർമാറ്റുകൾ.',
      choose2Title: 'കോഴ്‌സ് കടവ്',
      choose2Text: 'സംഘടിത മോഡ്യൂളുകൾ, വീഡിയോകൾ, ഒപ്പം അഭ്യാസങ്ങൾ യഥാർത്ഥ പഠനത്തിന് പിന്തുണ നൽകുന്നു.',
      choose3Title: 'ഗഹന വിശകലനം',
      choose3Text: 'പുരോഗതി ഡാഷ്ബോർഡുകൾ, സ്കോർ വിതരണം, ബലങ്ങളുടെ ഒരു വേഗതയുടെ ഉൾക്കാഴ്ച.',
      choose4Title: 'കയറിയർ- റെഡീ',
      choose4Text: 'ഇൻബിൽറ്റ് പ്ലേസ്‌മെന്റ് ഡ്രൈവ്, റാങ്കിംഗ് ബാധ്യത, റിസ്യൂമുകൾ-തയ്യാറുള്ള ട്രാക്കിംഗ്.',
      quickLinksTitle: 'ക്വിക് ലിങ്കുകൾ',
      quickLinksCourses: 'കോഴ്സുകൾ ബ്രൗസ് ചെയ്യുക, നിങ്ങളുടെ അടുത്ത പഠന പാതയിൽ രജിസ്റ്റർ ചെയ്യുക.',
      quickLinksExams: 'സജീവ പരീക്ഷകളും പരിശീലന ടെസ്റ്റുകളിലേക്ക് ആക്സസ്.',
      quickLinksLeaderboard: 'റാങ്കിങ്ങ്, സ്കോർ പ്രവണതകൾ, ഉന്നത പ്രകടനം പരിശോധിക്കുക.',
      quickLinksDrives: 'ഉപലഭ്യമായ കമ്പനി ഡ്രൈവ് കാണുക, ഇപ്പോൾ അപേക്ഷിക്കുക.',
      getStartedTitle: 'ആധുനിക പരീക്ഷ പോർട്ടലുമായി നിങ്ങളുടെ യാത്ര ആരംഭിക്കുക.',
      studentPortal: 'വിദ്യാർത്ഥി പോര്ട്ടൽ',
      studentPortalText: 'അനുകൂല പരീക്ഷകൾ, പഠന വിശകലനങ്ങൾ, പ്ലേസ്‌മെന്റ്-തയാറായ യാത്ര.',
      adminPortal: 'അഡ്‌മിൻ പോർട്ടൽ',
      adminPortalText: 'പരീക്ഷകൾ നിർമ്മിക്കുക, പ്രകടനം സമీക്ഷിക്കുക, ആധുനിക ഡാഷ്ബോർഡ് ഉപയോഗിച്ച് ഡ്രൈവ് മാനേജ് ചെയ്യുക.',
    },
    auth: {
      signInTitle: 'നിങ്ങളുടെ അക്കൗണ്ടിലേക്ക് സൈൻ ഇൻ ചെയ്യുക',
      registerTitle: 'നിങ്ങളുടെ അക്കൗണ്ട് സൃഷ്ടിക്കുക',
      createAccountLink: 'ഒരു പുതിയ അക്കൗണ്ട് സൃഷ്ടിക്കുക',
      signInLink: 'അതേ നിലവിലുള്ള അക്കൗണ്ടിലേക്ക് സൈൻ ഇൻ ചെയ്യുക',
      emailAddress: 'ഇമെയിൽ വിലാസം',
      password: 'പാസ്വേഡ്',
      signIn: 'സൈൻ ഇൻ',
      signingIn: 'സൈൻ ഇൻ ചെയ്യുന്നു...',
      fullName: 'പൂർണ്ണ പേര്',
      confirmPassword: 'പാസ്വേഡ് സ്ഥിരീകരിക്കുക',
      role: 'പങ്ക്',
      student: 'വിദ്യാർത്ഥി',
      admin: 'അഡ്‌മിൻ',
      createAccount: 'അക്കൗണ്ട് സൃഷ്ടിക്കുക',
      creatingAccount: 'അക്കൗണ്ട് സൃഷ്ടിക്കുന്നു...',
      passwordsMismatch: 'പാസ്വേഡ് സറി അല്ല',
    },
    dashboard: {
      welcome: 'നിങ്ങളുടെ ഡാഷ്ബോർഡിലേക്ക് സ്വാഗതം, {name}!',
      totalUsers: 'മൊത്തം ഉപയോക്താക്കൾ',
      totalExams: 'മൊത്തം പരീക്ഷകൾ',
      totalCourses: 'മൊത്തം കോഴ്സുകൾ',
      totalSubmissions: 'മൊത്തം സമർപ്പണങ്ങൾ',
      coursesEnrolled: 'എൻറോൾ ചെയ്ത കോഴ്സുകൾ',
      examsTaken: 'തെടുത്ത പരീക്ഷകൾ',
      averageScore: 'ശരാശരി സ്കോൾ',
      passedExams: 'പാസാക്കിയ പരീക്ഷകൾ',
      loading: 'ഡാഷ്ബോർഡ് ലോഡ് ചെയ്യുന്നു...',
      loginRequired: 'ഡാഷ്ബോർഡിലെ പ്രവേശനം ലഭിക്കാൻ ദയവായി ലോഗിന് ചെയ്യുക',
      scoreDistribution: 'സ്കോർ വിതരണം',
      monthlyPerformance: 'മാസാന്ത്യ പ്രകടനം (കഴിഞ്ഞ 6 മാസം)',
      courseProgress: 'കോഴ്‌സ് പുരോഗതി',
      examsTakenLabel: 'തെടുത്തു പരീക്ഷകൾ',
      averageScoreLabel: 'ശരാശരി സ്കോർ (%)',
      progressLabel: 'പുരോഗതി (%)',
    },
    courses: {
      title: 'കോഴ്സുകൾ',
      addCourse: 'പുതിയ കോഴ്സ് ചേർക്കുക',
      allCourses: 'എല്ലാ കോഴ്സുകളും',
      myCourses: 'എന്റെ കോഴ്സുകൾ',
      searchPlaceholder: 'കോഴ്സുകൾ തിരയുക...',
      allLevels: 'എല്ലാ നിലകളും',
      beginner: 'ആദ്യം',
      intermediate: 'ഇടത്തരം',
      advanced: 'മുന്നേർച',
      instructor: 'ഇൻസ്ട്രക്ടർ',
      hours: 'മണിക്കൂർ',
      enroll: 'ഒരുൾക്കുക',
      enrolled: 'രജിസ്റ്റർ ചെയ്തിരിക്കുന്നു',
      noCoursesMatch: 'നിങ്ങളുടെ തിരച്ചിലിന് യോജിക്കുന്ന കോഴ്സ് ഒന്നുമില്ല.',
      noEnrolled: 'നിങ്ങൾ ഇനിയും ഏതെങ്കിലും കോഴ്സിൽ ചേർക്കപ്പെട്ടിട്ടില്ല.',
      loading: 'കോഴ്സുകൾ ലോഡ് ചെയ്യുന്നു...',
    },
    exams: {
      title: 'പരീക്ഷകൾ',
      duration: 'ദൈർഘ്യം:',
      totalMarks: 'മൊത്തം മാർക്ക്:',
      difficulty: 'കഠിനത:',
      passed: 'എഴുത്ത്',
      failed: 'മോശം',
      alreadySubmitted: 'ഇതിനകം സമർപ്പിച്ചിരിക്കുന്നു',
      reviewExam: 'പരീക്ഷ പരിശോധിക്കുക',
      takeExam: 'പരീക്ഷ എടുക്കുക',
      loginToTakeExam: 'പരീക്ഷ എടുക്കാൻ ലോഗിൻ ചെയ്യുക',
      noExams: 'ഈ സമയം പരീക്ഷകൾ ലഭ്യമല്ല.',
      loading: 'പരീക്ഷകൾ ലോഡ് ചെയ്യുന്നു...',
      timerLabel: 'ടൈമർ:',
      passingScore: 'പാസിംഗ് സ്കോർ:',
      examSubmitted: 'പരീക്ഷ സമർപ്പിച്ചു',
      scoreLabel: 'സ്‌കോർ:',
      percentageLabel: 'ശതമാനം:',
      statusLabel: 'നില:',
      submitExam: 'പരീക്ഷ സമർപ്പിക്കുക',
      submitting: 'സമർപ്പിക്കുന്നു...',
      timeUp: 'സമയം തീങ്ങി. ഇപ്പോൾ നിങ്ങളുടെ ഉത്തരങ്ങൾ സമർപ്പിക്കുക.',
      answerPlaceholder: 'നിങ്ങളുടെ ഉത്തരങ്ങൾ ഇവിടെ എഴുതുക',
      selectLanguage: 'പ്രോഗ്രാമിംഗ് ഭാഷ തിരഞ്ഞെടുക്കൂ:',
      codePlaceholder: '{language} കോഡ് സൊല്യൂഷൻ ഇവിടെ എഴുതുക...',
      loginRequired: 'ഈ പരീക്ഷ എടുക്കാൻ ദയവായി ലോഗിൻ ചെയ്യുക.',
      examNotFound: 'പരീക്ഷ കണ്ടെത്തിയില്ല.',
      noQuestions: 'ഈ പരീക്ഷക്ക് ഇനിയും ചിലപ്പോഴുള്ള ചോദ്യം ഇല്ല.',
    },
    drives: {
      title: 'പ്ലേസ്‌മെന്റ് ഡ്രൈവ്‌లు',
      subtitle: 'കമ്പനി പ്ലേസ്‌മെന്റ് ഡ്രൈവ് നടത്തിപ്പിന് അപേക്ഷിക്കുക',
      applyNow: 'ഇപ്പൊ തന്നെ അപേക്ഷിക്കുക',
      deadlinePassed: 'അവസാന തീയതി കഴിഞ്ഞു',
      noDrives: 'ഈ സമയം സജീവമായ പ്ലേസ്‌മെന്റ് ഡ്രൈവ് ലഭ്യമല്ല.',
      loading: 'ഡ്രൈവ് ലോഡ് ചെയ്യുന്നു...',
      applyFor: 'ഇതിന് അപേക്ഷിക്കുക',
      fullName: 'പൂർണ്ണ Name *',
      email: 'ഇമെയിൽ *',
      cgpa: 'CGPA *',
      phone: 'ഫോൺ നമ്പർ',
      address: 'വിലാസം',
      skills: 'തிறമകൾ',
      experience: 'പരിചയം',
      submitApplication: 'അപ്ലിക്കേഷൻ സമർപ്പിക്കുക',
      applicationSubmitted: 'അപ്ലിക്കേഷൻ വിജയകരമായി സമർപ്പിച്ചു!',
    },
    contact: {
      titleSmall: 'ബന്ധപ്പെടുക',
      title: 'നിങ്ങളുടെ വിജയത്തിന് ഞങ്ങൾ സഹായിക്കാൻ ഇവിടെ ഉണ്ട്.',
      subtitle: 'കോഴ്‌സുകൾ, പരീക്ഷകൾ, അല്ലെങ്കിൽ അഡ്മിൻ സവിശേഷതകളെക്കുറിച്ച് ചോദിക്കാനുണ്ടോ? ഞങ്ങൾക്ക് സന്ദേശം അയയ്ക്കൂ.',
      emailTitle: 'ഇമെയിൽ',
      phoneTitle: 'ഫോൺ',
      officeTitle: 'ഓഫീസ്',
      officeText: 'ഓൺലൈൻ പഠന പ്ലാറ്റ്ഫോം — ആഗോളമായി ലഭ്യമാണ്.',
      name: 'പേര്',
      message: 'സന്ദേശം',
      sendMessage: 'സന്ദേശം അയയ്ക്കുക',
      thankYou: 'നന്ദി! നിങ്ങളുടെ സന്ദേശം സ്വീകരിച്ചു.',
    },
    profile: {
      title: 'പ്രൊഫൈൽ',
      editProfile: 'പ്രൊഫൈൽ എഡിറ്റ് ചെയ്യുക',
      save: 'സേവ്',
      cancel: 'റദ്ദാക്കിയിരിക്കുക',
      saving: 'സേവ് ചെയ്യുന്നു...',
      profileSaved: 'പ്രൊഫൈൽ വിജയകരമായി സേവ് ചെയ്തു.',
      loginRequired: 'പ്രൊഫൈൽ ആക്സസ് ചെയ്യാൻ ദയവായി ലോഗിൻ ചെയ്യുക.',
      name: 'പേര്',
      email: 'ഇമെയിൽ',
      role: 'പങ്ക്',
      placementInfo: 'പ്ലേസ്‌മെന്റ് വിവരങ്ങൾ',
      phoneNumber: 'ഫോൺ നമ്പർ',
      cgpa: 'CGPA',
      address: 'വിലാസം',
      skills: 'തிறമകൾ',
      experience: 'പരിചയം',
      profileImage: 'പ്രൊഫൈൽ ചിത്രം URL',
      notProvided: 'സമർപ്പിച്ചിട്ടില്ല',
    },
    footer: {
      description: 'ഇന്ററാക്ടീവ് പരീക്ഷകൾ, കോഴ്‌സുകൾ, വിശകലനങ്ങൾ എന്നിവയിലൂടെ പഠകരെ ശക്തിപ്പെടുത്തുന്നു.',
      allRights: 'എല്ലാ അവകാശങ്ങളും സംരക്ഷിക്കപ്പെട്ടിരിക്കുന്നു.',
    },
    notFound: {
      pageNotFound: 'പേജ് കാണാനില്ല',
      message: 'നിങ്ങൾ കാണാൻ ശ്രമിക്കുന്ന പേജ് നിലവിലില്ല. ഹോംപേജിലേക്ക് തിരികെ പോകുക.',
    },
    admin: {
      dashboardTitle: 'അഡ്‌മിൻ ഡ്യാഷ്‍ബോർഡ്',
      manageUsers: 'ഉപയോക്താക്കളെ നിയന്ത്രിക്കുക',
      manageUsersText: 'എല്ലാ ഉപയോക്താക്കളെയും കാണുകയും നിയന്ത്രിക്കുകയും ചെയ്യുക',
      createExam: 'പരീക്ഷ സൃഷ്ടിക്കുക',
      createExamText: 'ചോദ്യങ്ങളോടുകൂടിയ പുതിയ പരീക്ഷകൾ സൃഷ്ടിക്കുക',
      manageCourses: 'കോഴ്സുകൾ നിയന്ത്രിക്കുക',
      manageCoursesText: 'കോഴ്സ് ഉള്ളടക്കം ചേർക്കുകയും നിയന്ത്രിക്കുകയും ചെയ്യുക',
      createCourse: 'കോഴ്സ് സൃഷ്ടിക്കുക',
      courseBuilderTitle: 'അഡ്‌മിൻ കോഴ്‌സ് നിർമാണം',
      createNewCourse: 'പുതിയ കോഴ്‌സ് സൃഷ്ടിക്കുക',
      manageCoursesTitle: 'കോഴ്സുകൾ നിയന്ത്രിക്കുക',
      modulesForCourse: '{title} യ്ക്കുള്ള മോഡ്യൂൾസ്',
      addModule: 'മോഡ്യൂൾ ചേർക്കുക',
      createCourseSuccess: 'കോഴ്സ് സൃഷ്ടിച്ചു. ഇനി നിങ്ങൾ മോഡ്യൂളുകൾ ചേർക്കാമ.',
      moduleAdded: 'മോഡ്യൂൾ വിജയകരമായി ചേർത്തു',
      createCourseButton: 'കോഴ്സ് സൃഷ്ടിക്കുക',
      refreshModules: 'മോഡ്യൂൾസ് റിഫ്രെഷ് ചെയ്യുക',
      editDrive: 'ഡ്രൈവിനെ എഡിറ്റ് ചെയ്യുക',
      createNewDrive: 'പുതിയ ഡ്രൈവ് സൃഷ്ടിക്കുക',
      managePlacementDrives: 'പ്ലേസ്‌മെന്റ് ഡ്രൈവ്‌സ് നിയന്ത്രിക്കുക',
      managePlacementDrivesText: 'കമ്പനി പ്ലേസ്‌മെന്റ് ഡ്രൈവ്‌സ് സൃഷ്ടിക്കുകയും നിയന്ത്രിക്കുകയും ചെയ്യുക',
      createDrive: 'ഡ്രൈവ് സൃഷ്ടിക്കുക',
      active: 'സജീവം',
      inactive: 'നിശ്ചലമാണ്',
      viewApplications: 'അപ്ലിക്കേഷനുകൾ കാണുക',
      deleteDriveConfirm: 'ഈ ഡ്രൈവിനെ നിങ്ങൾ ખર്യമായും നീക്കം ചെയ്യണോ?',
      errorSaveDrive: 'ഡ്രൈവ് സേവ് ചെയ്യുന്നതിൽ പിശക്',
      noDrives: 'ഇപ്പോൾ വരെ ഡ്രൈവ് സൃഷ്ടിച്ചിട്ടില്ല. ആദ്യ ഡ്രൈവ് ചേരാൻ "Create Drive" അമർത്തുക.',
    },
  },
  ta: {
    nav: {
      home: 'ஹோம்',
      courses: 'பாடங்கள்',
      exams: 'தேர்வுகள்',
      leaderboard: 'தலைசீட்டு படிவம்',
      drives: 'ஏர்கள்',
      contact: 'தொடர்பு',
      dashboard: 'டாஷ்போர்ட்',
      createExam: 'தேர்வு உருவாக்கு',
      manageDrives: 'ஏர்களை நிர்வகிக்கவும்',
      profile: 'சுயவிவரம்',
      login: 'உள் நுழைவு',
      register: 'பதிவு',
      logout: 'வெளியேறு',
      language: 'மொழி',
    },
    theme: {
      light: 'ஒளி',
      dark: 'இருள்',
    },
    landing: {
      heroBadge: 'எதிர்காலத்துக்கு தயாரான தேர்வு தளம்',
      heroTitle: 'கற்றலாளர்களுக்கும் ஆசிரியர்களுக்கும் ஒரு புத்திசாலித்தனமான தேர்வு அனுபவம்.',
      heroSubtitle: 'EduPortal தன்னிச்சையான மதிப்பீடுகள், வேலைவாய்ப்பு தயாரான பகுப்பாய்வு மற்றும் ஒத்துழைப்பு வழிகாட்டுதலை ஒருங்கிணைக்கிறது.',
      exploreDrives: 'வேலைநிறுத்தங்களை பார்க்கவும்',
      viewLeaderboard: 'தலைசீட்டைப் பார்க்கவும்',
      trustedBy: 'கற்றலாளர்கள் நம்புகின்றனர்',
      studentLogin: 'மாணவர் புகுபதிகை',
      adminLogin: 'நிர்வாகி புகுபதிகை',
      advancedTitle: 'மற்ற எந்த தேர்வு தளத்திலிருந்து வித்தியாசமாக உணரப்பட하도록 வடிவமைக்கப்பட்டது.',
      advancedSubtitle: 'புத்திசாலித்தனமான வழிகாட்டுதல், நேரடி வேலைவாய்ப்பு தயாரிப்பு மற்றும் குறைமையேற்ற தேர்வு அனுபவங்கள் உங்களை ஈர்க்கின்றன.',
      feature1Title: 'AI இயக்கப்பட்ட படிப்பு பயிற்சி',
      feature1Text: 'உங்கள் முன்னேற்றம் அடிப்படையில் தனிப்பயன் மறுசீரமைப்பு குறிப்புகள், கேள்வி பரிந்துரைகள் மற்றும் தேர்வு தயாரிப்பு தகவல்களைப் பெறவும்.',
      feature2Title: 'உகந்த தேர்வு ஓட்டம்',
      feature2Text: 'உங்கள் வேகம் மற்றும் செயல்பாட்டுக்கு ஏற்ப தேர்வுகள் மிகவும் சவாலானதாகவும் துரிதமான வெற்றித் தடவையாகவும் இருக்கும்.',
      feature3Title: 'வேலைவாய்ப்பு ஓட்டக் கூடம்',
      feature3Text: 'உண்மையான நிறுவன ஓட்டங்களை கண்டறியவும், உங்கள் சுயவிவரத்துடன் விண்ணப்பிக்கவும் மற்றும் வேலைவாய்ப்பு தயாரிப்பை தொடருங்கள்.',
      chooseTitle: 'EduPortal ஐ ஏன் தேர்வு செய்கிறீர்கள்?',
      choose1Title: 'இணையமுள்ள தேர்வுகள்',
      choose1Text: 'உண்மையான நேர மதிப்பீடு, உடனடி பின்னூட்டம் மற்றும் ஈர்க்கக்கூடிய தேர்வு வடிவங்கள்.',
      choose2Title: 'பாடம் நிபுணத்துவம்',
      choose2Text: 'ஒழுங்குபடுத்தப்பட்ட தொகுதிகள், வீடியோக்கள் மற்றும் பயிற்சிகள் உண்மையான கற்றலுக்கு ஆதரவாகும்.',
      choose3Title: 'ஆழமான பகுப்பாய்வு',
      choose3Text: 'முன்னேற்ற டாஷ்போர்டுகள், மதிப்பெண் பகிர்வு மற்றும் பலம் கண்காணிப்பு.',
      choose4Title: 'கேரியர்-தயார்',
      choose4Text: 'இணைப்பட்ட வேலைவாய்ப்பு ஓட்டங்கள், தரவரிசை தாக்கம் மற்றும் ரெச்யூம்-தயாரிப்பு கண்காணிப்பு.',
      quickLinksTitle: 'விரைவு இணைப்புகள்',
      quickLinksCourses: 'பாடங்களை உலாவவும் மற்றும் உங்கள் அடுத்த கற்றல் பாதையில் சேரவும்.',
      quickLinksExams: 'சுயமுயற்சி தேர்வுகள் மற்றும் பயிற்சி பரீட்சைகளுக்கு அணுகவும்.',
      quickLinksLeaderboard: 'தரவரிசைகள், மதிப்பெண் போக்குகள் மற்றும் சிறந்த செயல்திறனை சரிபார்க்கவும்.',
      quickLinksDrives: 'கிடைக்கும் நிறுவனர் ஓட்டங்களைப் பார்க்கவும் மற்றும் இப்போதே விண்ணப்பிக்கவும்.',
      getStartedTitle: 'ஆधুনீக தேர்வு தளத்துடன் உங்கள் பயணத்தைத் தொடங்குங்கள்.',
      studentPortal: 'மாணவர் போர்ட்டல்',
      studentPortalText: 'உகந்த தேர்வுகள், கற்றல் பகுப்பாய்வு மற்றும் வேலைவாய்ப்பு தயார் பயணம்.',
      adminPortal: 'நிர்வாகி போர்ட்டல்',
      adminPortalText: 'தேர்வுகளை உருவாக்கவும், செயல்திறனை மதித்தெடுக்கவும் மற்றும் சிறந்த டாஷ்போர்டுடன் ஓட்டங்களை நிர்வகிக்கவும்.',
    },
    auth: {
      signInTitle: 'உங்கள் கணக்கில் உள்நுழைக',
      registerTitle: 'உங்கள் கணக்கை உருவாக்கவும்',
      createAccountLink: 'புதிய கணக்கை உருவாக்கவும்',
      signInLink: 'இருப்புள்ள கணக்கில் உள்நுழைக',
      emailAddress: 'மின்னஞ்சல் முகவரி',
      password: 'கடவுச்சொல்',
      signIn: 'உள்நுழை',
      signingIn: 'உள்நுழைகிறது...',
      fullName: 'முழு பெயர்',
      confirmPassword: 'கடவுச்சொல்லை உறுதிப்படுத்தவும்',
      role: 'நிலை',
      student: 'மாணவன்',
      admin: 'நிர்வாகி',
      createAccount: 'கணக்கை உருவாக்கவும்',
      creatingAccount: 'கணக்கை உருவாக்குகிறது...',
      passwordsMismatch: 'கடவுச்சொற்கள் பொருந்தவில்லை',
    },
    dashboard: {
      welcome: 'உங்கள் டாஷ்போர்டுக்கு வரவேற்கிறோம், {name}!',
      totalUsers: 'மொத்த பயனர்கள்',
      totalExams: 'மொத்த தேர்வுகள்',
      totalCourses: 'மொத்த பாடங்கள்',
      totalSubmissions: 'மொத்த சமர்ப்பிப்புகள்',
      coursesEnrolled: 'சேர்ந்த பாடங்கள்',
      examsTaken: 'நீங்கள் எடுத்த தேர்வுகள்',
      averageScore: 'சராசரி மதிப்பெண்',
      passedExams: 'தேர்வுகள் நீக்கப்பட்டன',
      loading: 'டாஷ்போர்டு ஏற்றுகிறது...',
      loginRequired: 'டாஷ்போர்டுக்கு அணுக, தயவுசெய்து உள்நுழைக',
      scoreDistribution: 'மதிப்பெண் பகிர்வு',
      monthlyPerformance: 'மாதாந்திர செயல்திறன் (கடந்த 6 மாதங்கள்)',
      courseProgress: 'பாடநெறி முன்னேற்றம்',
      examsTakenLabel: 'கடுக்கப்பட்ட தேர்வுகள்',
      averageScoreLabel: 'சராசரி மதிப்பெண் (%)',
      progressLabel: 'முன்னேற்றம் (%)',
    },
    courses: {
      title: 'பாடங்கள்',
      addCourse: 'புதிய பாடம் சேர்',
      allCourses: 'அனைத்து பாடங்கள்',
      myCourses: 'எனது பாடங்கள்',
      searchPlaceholder: 'பாடங்களை தேடு...',
      allLevels: 'அனைத்து நிலைகளும்',
      beginner: 'ஆரம்ப',
      intermediate: 'நடுத்தர',
      advanced: 'உயர்',
      instructor: 'பயிற்றுநர்',
      hours: 'மணி',
      enroll: 'சேரவும்',
      enrolled: 'சேர்வினர்',
      noCoursesMatch: 'உங்கள் தேடுதலுக்கு பொருந்தும் பாடங்கள் எதுவுமில்லை.',
      noEnrolled: 'நீங்கள் இன்னும் எந்த பாடத்திலும் சேரவில்லைய.',
      loading: 'பாடங்கள் ஏற்றப்படுகிறது...',
    },
    exams: {
      title: 'தேர்வுகள்',
      duration: 'காலம்:',
      totalMarks: 'மொத்த மதிப்பெண்கள்:',
      difficulty: 'பிரயாணம்:',
      passed: 'ஏற்றுக்கொள்',
      failed: 'தோல்வி',
      alreadySubmitted: 'ஏற்கெனவே சமர்ப்பிக்கப்பட்டது',
      reviewExam: 'தேர்வினை மதிப்பீடு செய்',
      takeExam: 'தேர்வை எடு',
      loginToTakeExam: 'தேர்வு எடுக்க உள்நுழைக',
      noExams: 'தற்போது எந்த தேர்வுகளும் இல்லை.',
      loading: 'தேர்வுகள் ஏற்றப்படுகிறது...',
      timerLabel: 'டைமர்:',
      passingScore: 'ஏற்ற மதிப்பெண்:',
      examSubmitted: 'தேர்வு சமர்ப்பிக்கப்பட்டது',
      scoreLabel: 'மதிப்பெண்:',
      percentageLabel: 'சதவீதம்:',
      statusLabel: 'நிலை:',
      submitExam: 'தேர்வை சமர்ப்பிக்கவும்',
      submitting: 'சமர்ப்பிக்கப்படுகிறது...',
      timeUp: 'நேரம் முடிந்துவிட்டது. இப்போது உங்கள் பதில்களை சமர்ப்பிக்கவும்.',
      answerPlaceholder: 'உங்கள் பதிலை இங்கே எழுதவும்',
      selectLanguage: 'ப்ரோகிராமிங் மொழியை தேர்வு செய்க:',
      codePlaceholder: '{language} குறியீட்டு தீர்வை இங்கே எழுதவும்...',
      loginRequired: 'இந்த தேர்வை எடுக்க உள்நுழைக.',
      examNotFound: 'தேர்வு கிடைக்கவில்லை.',
      noQuestions: 'இந்த தேர்வில் இன்னும் கேள்விகள் இல்லை.',
    },
    drives: {
      title: 'பிளேஸ்மெண்ட் டிரைவ்ஸ்',
      subtitle: 'நிறுவன பிளேஸ்மெண்ட் டிரைவ்ஸுக்கு விண்ணப்பிக்கவும்',
      applyNow: 'இப்போதே விண்ணப்பிக்கவும்',
      deadlinePassed: 'கடைசிநாள் கடந்தது',
      noDrives: 'தற்போது செயல்பாட்டில் உள்ள டிரைவ்ஸ்கள் எதுவுமில்லை.',
      loading: 'டிரைவ்ஸ்கள் ஏற்றப்படுகிறது...',
      applyFor: 'விண்ணப்பிக்க',
      fullName: 'முழு பெயர் *',
      email: 'மின்னஞ்சல் *',
      cgpa: 'CGPA *',
      phone: 'தொலைபேசி எண்',
      address: 'முகவரி',
      skills: 'திறன்கள்',
      experience: 'பிபெர விளக்கம்',
      submitApplication: 'விண்ணப்பத்தைக் சமர்ப்பிக்கவும்',
      applicationSubmitted: 'விண்ணப்பம் வெற்றிகரமாக சமர்ப்பிக்கப்பட்டது!',
    },
    contact: {
      titleSmall: 'தொடர்பு கொள்ளவும்',
      title: 'உங்கள் வெற்றிக்கு நாங்கள் உதவ כאן இருக்கிறோம்.',
      subtitle: 'பாடங்கள், தேர்வுகள், அல்லது நிர்வாக சன்மானங்களைப் பற்றி கேள்விகள் உள்ளதா? எங்களுக்கு ஒரு செய்தி அனுப்புங்கள்.',
      emailTitle: 'மின்னஞ்சல்',
      phoneTitle: 'தொலைபேசி',
      officeTitle: 'ஆஃபிஸ்',
      officeText: 'ஆன்லைன் கற்றல் தளம் — உலகளாவியமாக கிடைக்கும்.',
      name: 'பெயர்',
      message: 'செய்தி',
      sendMessage: 'செய்தியை அனுப்பு',
      thankYou: 'நன்றி! உங்கள் செய்தி கிடைத்துவிட்டது.',
    },
    profile: {
      title: 'சுயவிவரம்',
      editProfile: 'சுயவிவரத்தை திருத்து',
      save: 'சேமிக்கவும்',
      cancel: 'ரத்துச் செய்',
      saving: 'சேமிப்பது...',
      profileSaved: 'சுயவிவரம் வெற்றிகரமாக சேமிக்கப்பட்டது.',
      loginRequired: 'சுயவிவரத்தை அணுக உள்நுழைக.',
      name: 'பெயர்',
      email: 'மின்னஞ்சல்',
      role: 'பாத்திரம்',
      placementInfo: 'பிளேஸ்மெண்ட் தகவல்',
      phoneNumber: 'தொலைபேசி எண்',
      cgpa: 'CGPA',
      address: 'முகவரி',
      skills: 'திறன்கள்',
      experience: 'அனுபவம்',
      profileImage: 'சுயவிவர படத் URL',
      notProvided: 'கிடைக்கவில்லை',
    },
    footer: {
      description: 'இணையமுற்று தேர்வுகள், பாடங்கள் மற்றும் பகுப்பாய்வுகளுடன் கற்றலாளர்களை சக்திவாய்ந்தவையாக மாற்றுகிறது.',
      allRights: 'அனைத்து உரிமைகளும் பாதுகாக்கப்பட்டவை.',
    },
    notFound: {
      pageNotFound: 'பக்கம் காணப்படவில்லை',
      message: 'நீங்கள் தேடும் பக்கம் இல்லை. முகப்புப் பக்கம் அல்லது செயல்பாட்டு பலகையைக் கடந்து செல்லவும்.',
    },
    admin: {
      dashboardTitle: 'அட்மின் டாஷ்போர்டு',
      manageUsers: 'பயனர்களை நிர்வகி',
      manageUsersText: 'அனைத்து பயனர்களையும் காண்க மற்றும் நிர்வகி',
      createExam: 'பரீட்சை உருவாக்கு',
      createExamText: 'கேள்விகளுடன் புதிய பரீட்சைகள் உருவாக்கு',
      manageCourses: 'நிறுவனங்களை நிர்வகி',
      manageCoursesText: 'கோর্স் உள்ளடக்கம் சேர்க்கவும் மற்றும் நிர்வகிக்கவும்',
      createCourse: 'கோர்ஸ் உருவாக்கு',
      courseBuilderTitle: 'அட்மின் கோர்ஸ் கட்டப்பட்டது',
      createNewCourse: 'புதிய கோர்ஸ் உருவாக்கு',
      manageCoursesTitle: 'கோர்ஸ்களை நிர்வகி',
      modulesForCourse: '{title} க்கான மாட்யூல்கள்',
      addModule: 'மாட்யூலைச் சேர்க்கவும்',
      createCourseSuccess: 'கோர்ஸ் உருவாக்கப்பட்டது. இப்போது நீங்கள் மாட்யூல்கள் சேர்க்கலாம்.',
      moduleAdded: 'மாட்யூல் வெற்றிகரமாக சேர்க்கப்பட்டது',
      createCourseButton: 'கோர்ஸ் உருவாக்கு',
      refreshModules: 'மாட்யூல்கள் புதுப்பிக்கவும்',
      editDrive: 'டிரைவ் திருத்தவும்',
      createNewDrive: 'புதிய டிரைவ் உருவாக்கவும்',
      managePlacementDrives: 'பிளேஸ்மெண்ட் டிரைவ் நிர்வாகம்',
      managePlacementDrivesText: 'நிறுவன பிளேஸ்மெண்ட் டிரைவ் உருவாக்கவும் மற்றும் நிர்வகிக்கவும்',
      createDrive: 'டிரைவ் உருவாக்கவும்',
      active: 'செயலில்',
      inactive: 'செயலற்றது',
      viewApplications: 'விண்ணப்பங்களைப் பார்க்கவும்',
      deleteDriveConfirm: 'இந்த டிரைவ் நீக்கப்பட வேண்டுமா?',
      errorSaveDrive: 'டிரைவை சேமிப்பதில் பிழை',
      noDrives: 'இன்னும் எந்த டிரைவும் உருவாகவில்லை. முதன்மை டிரைவ் சேர்க்க Create Drive ஐ கிளிக் செய்.',
    },
  },
};

const AppSettingsContext = createContext(null);

const getInitialTheme = () => {
  const stored = localStorage.getItem('theme');
  const prefersDark = window.matchMedia?.('(prefers-color-scheme: dark)').matches;
  return stored ? stored : prefersDark ? 'dark' : 'light';
};

const getInitialLanguage = () => {
  const stored = localStorage.getItem('language');
  return stored || 'en';
};

const resolveKey = (obj, key) => {
  return key.split('.').reduce((acc, part) => (acc && acc[part] !== undefined ? acc[part] : null), obj);
};

export const AppSettingsProvider = ({ children }) => {
  const [theme, setTheme] = useState(getInitialTheme);
  const [language, setLanguage] = useState(getInitialLanguage);

  useEffect(() => {
    const root = document.documentElement;
    root.classList.toggle('dark', theme === 'dark');
    root.style.colorScheme = theme === 'dark' ? 'dark' : 'light';
    localStorage.setItem('theme', theme);
  }, [theme]);

  useEffect(() => {
    document.documentElement.lang = language;
    localStorage.setItem('language', language);
  }, [language]);

  const t = (key, values = {}) => {
    const languageObject = translations[language] || translations.en;
    let text = resolveKey(languageObject, key) || resolveKey(translations.en, key) || key;

    Object.keys(values).forEach((valueKey) => {
      text = text.replace(`{${valueKey}}`, values[valueKey]);
    });

    return text;
  };

  const value = useMemo(
    () => ({
      theme,
      isDark: theme === 'dark',
      toggleTheme: () => setTheme((prev) => (prev === 'dark' ? 'light' : 'dark')),
      language,
      setLanguage,
      languages,
      t,
    }),
    [theme, language]
  );

  return <AppSettingsContext.Provider value={value}>{children}</AppSettingsContext.Provider>;
};

export const useAppSettings = () => {
  const context = useContext(AppSettingsContext);
  if (!context) {
    throw new Error('useAppSettings must be used within AppSettingsProvider');
  }
  return context;
};
